# This TOML file has an array of probes [[probe]]


[[probe]]
type = "hotwire"
# Number of wires or resistance elements
nwires = 1
descr = "A hotwire CTA, with linear probe Description of the sensor/etc"
# Tag for the sensor
tag = "XYZ"

# Configuration of the hardware
[probe.cta]
R = 6.3 

# Data acaquisition device
[probe.device]
device = "Dev1"
channel = 1

# Resistance element
[probe.resistance]
# The type of resistance element.
# For a linear resistance, R = R0.(1 + a.(T-T0))
type = "linear"  # Could be 'thermistor'
R = 3.5 # Reference resistance (Ohms)
a = 0.4e-2 # Linear coefficient K^(-1)
T = 298.15 # Reference temperature. Try to use SI units, K
[probe.calibration]
# Calibration velocity
U = [0.504, 0.658, 0.858, 1.111, 1.451, 1.900, 2.440, 3.205, 4.144, 5.364, 6.893, 9.114, 11.708, 15.078, 19.931]
# Calibration voltage
E = [1.469, 1.495, 1.523, 1.555, 1.592, 1.633, 1.674, 1.723, 1.771, 1.823, 1.877, 1.943, 2.009, 2.081, 2.166]
T = 24.0 # Calibration temperature. Could be an array for each calibration point.
P = 92.65 # Calibration pressure. Could be an array for each calibration point.

# Calibration fluid
# If a string is used, it should be something available in src/fluid.jl
fluid = "AIR"


[[probe]]
# Number of wires
N = 1
descr = "A thermistor CTA sensor"
# Tag for the sensor
tag = "XYZ"

# Configuration of the hardware
[probe.hardware]
type = "" # Dantec Streamline
 
# Operation mode: CTA or CCA. Default is CTA!
mode = "CTA"
# For CTA, we need to specify the operating resistance
R = 100

[probe.device]
device = "epsmcp"
channel = 4

# Resistance element
[probe.resistance]
# The type of resistance element.
# For a linear resistance, R = R0.(1 + a.(T-T0))
type = "ntc"  # Could be 'NTC'
R = 5e3 # Reference resistance (Ohms)
B = 3950 # B coefficient
T = 298.15 # Reference temperature. Try to use SI units, K


[probe.calibration]
# Calibration velocity
U = [0.504, 0.658, 0.858, 1.111, 1.451, 1.900, 2.440, 3.205, 4.144, 5.364, 6.893, 9.114, 11.708, 15.078, 19.931]
# Calibration voltage
E = [1.469, 1.495, 1.523, 1.555, 1.592, 1.633, 1.674, 1.723, 1.771, 1.823, 1.877, 1.943, 2.009, 2.081, 2.166]
T = 24.0 # Calibration temperature. Could be an array for each calibration point.
P = 92.65 # Calibration pressure. Could be an array for each calibration point.
# Calibration fluid
# If a string is used, it should be something available in src/fluid.jl
fluid = "AIR"



